### ISSUE TITLE
[traj_simu/dt] Finding a better default `traj_dt` for non-adaptive method or give option to use adaptive method

### ISSUE THREAD

**Issue by TheStarAlight** [TheStarAlight/SemiclassicalSFI.jl#16]
The program runs too slow under the current default `traj_dt=0.1`, thus we need to find out a better default value which reaches a balance between speed and accuracy.
Anyone who did test on this is welcomed to post his/her suggestions here!

**Comment by kfwu** [comment]
If you like I could run different simulations using different **traj_dt** and compare the results from this Package with TDSE results from Qprop. I think for different atoms and lights different parameter is needed.

**Comment by TheStarAlight** [comment]
@kfwu Yes I agree, the parameters should be set according to different situations. I would be grateful if you can provide some valuable results. BTW, choose a lower Keldysh parameter if you would like to compare the results with those obtained from TDSE.

**Comment by TheStarAlight** [comment]
Fine, maybe the adaptive method is more appropriate, I'll try to figure out if it works for the latest DiffEqGPU. If it really works and the `rtol` takes effect, I'll switch to it as soon as possible.

**Comment by TheStarAlight** [comment]
It seems the adaptive method is much more favorable.

I performed a CPU ensemble simulation using adaptive method using the data from (`test/TrajectorySimulation_test.jl`)[https://github.com/TheStarAlight/SemiclassicalSFI.jl/blob/dev/test/TrajectorySimulation_test.jl] and found that time step is very large and it takes only ~30 steps from t=0 to t=120. However for non-adaptive method if we use `dt=0.1` it would be 1200 steps, no wonder it gets so slow...

I opened an issue in DiffEqGPU to ask if there is adaptive method available, if not, I'm consider giving an option to switch between adaptive and non-adaptive, since the adaptive method is more favorable, we should give user the option to decide.

```
julia> solc.u[1]
retcode: Success
Interpolation: specialized 4th order "free" interpolation
t: 31-element Vector{Float64}:
   0.0
   0.042866837667126505
   0.4715352143383915
   1.4141490655297164
   2.6573091978295054
   4.245611833739657
   6.226720682981561
   8.588974300182505
  11.313811267894188
  14.386011674538146
  17.78298419165096
  21.47979803486625
  25.46472953957726
  29.523680893019787
  33.16810937392944
  37.533822791844905
  42.14441297588711
  47.18047397848148
  52.433694162808635
  57.978022790361855
  63.75222768811929
  69.8131879851974
  76.18565210161074
  82.87906754704659
  89.81378022020958
  96.91477767482775
 104.2023709859679
 109.188703923687
 114.56514216141889
 118.05428034827725
 120.0
u: 31-element Vector{SVector{6, Float64}}:
 [10.0, 5.0, 0.0, 0.0, 1.0, 0.0]
 [9.999993469974697, 5.04281454100733, 0.0, -0.00030545565630656573, 0.9975599562466383, 0.0]
 [9.999168790453876, 5.465203613979251, 0.0, -0.003621604907508397, 0.973137711018667, 0.0]
 [9.991704758376859, 6.357170768135835, 0.0, -0.012606107846010902, 0.919414168000755, 0.0]
 [9.96684065003164, 7.456271419934138, 0.0, -0.028094089519165144, 0.8489383048683435, 0.0]
 [9.902521175386035, 8.734037870612266, 0.0, -0.05406545698251152, 0.7603925044889708, 0.0]
 [9.75536435305661, 10.134022344040797, 0.0, -0.09631640022735626, 0.6537851420241042, 0.0]
 [9.454690622966156, 11.535622670142036, 0.0, -0.16073749504233986, 0.534497427911531, 0.0]
 [8.89547085807191, 12.819539398874758, 0.0, -0.2527022287911034, 0.4105915183373621, 0.0]
 [7.934671145989035, 13.892975978923271, 0.0, -0.3758533930492746, 0.2922994586039381, 0.0]
 [6.400347602443347, 14.705879809405198, 0.0, -0.53002594480214, 0.19190510493919105, 0.0]
 [4.110851638992152, 15.273340903350292, 0.0, -0.709760833698424, 0.12211557201704817, 0.0]
 [0.8931093311995153, 15.688235207670601, 0.0, -0.9040853002168362, 0.0943030853228476, 0.0]
 [-3.156625133495997, 16.097647796036625, 0.0, -1.0878337698870155, 0.11556581334549168, 0.0]
 [-7.388590239282852, 16.61512913583724, 0.0, -1.230454327837949, 0.17425710131393837, 0.0]
 [-13.069751805770098, 17.604206002853797, 0.0, -1.3650534225667346, 0.2851726993520606, 0.0]
 [-19.598185530626324, 19.253112463960022, 0.0, -1.4581042157079245, 0.4338273586806284, 0.0]
 [-27.071057531413928, 21.87918422740447, 0.0, -1.4992093491658818, 0.6093053135348587, 0.0]
 [-34.92047549855535, 25.5415812542192, 0.0, -1.4794186480550742, 0.7811496696956715, 0.0]
 [-42.93504847109644, 30.297295296236182, 0.0, -1.4040587925498824, 0.9267118722172618, 0.0]
 [-50.725115305211915, 35.9571021458935, 0.0, -1.2905220214719004, 1.0237271770137228, 0.0]
 [-58.157671532011044, 42.31054443069227, 0.0, -1.16314785626625, 1.062537094523696, 0.0]
 [-65.19085117952173, 49.05399855292339, 0.0, -1.0497060998666796, 1.0457924483231897, 0.0]
 [-71.93423189301133, 55.882546369079975, 0.0, -0.973335092046451, 0.9907701350345408, 0.0]
 [-78.55392857953221, 62.523944716737695, 0.0, -0.9433694492096545, 0.9257981561759995, 0.0]
 [-85.25801709793024, 68.91006916159775, 0.0, -0.94894382102846, 0.8772794800059058, 0.0]
 [-92.23754303216954, 75.20947407659168, 0.0, -0.9662128329524222, 0.8560248773715193, 0.0]
 [-97.0741258213829, 79.46901542664428, 0.0, -0.9723787120112543, 0.8534074572079784, 0.0]
 [-102.30259298779688, 84.05663021944225, 0.0, -0.9723558946789846, 0.8531805782346704, 0.0]
 [-105.69501484299677, 87.03327953893992, 0.0, -0.9722072648798067, 0.8530583239664961, 0.0]
 [-107.58658063396847, 88.69302846315016, 0.0, -0.9721286105634978, 0.8529935196870115, 0.0]
```

**Comment by TheStarAlight** [comment]
Just did another test by switching `traj_dt` in the [`test/TrajectorySimulation_test.jl`](https://github.com/TheStarAlight/SemiclassicalSFI.jl/blob/dev/test/TrajectorySimulation_test.jl).

```
julia> solc = solve(ensemble_prob, OrdinaryDiffEq.Tsit5(), EnsembleThreads(), trajectories=size(init,2), adaptive=false, dt=0.01, save_everystep=false); solc.u[1]
retcode: Success
Interpolation: 1st order linear
t: 2-element Vector{Float64}:
   0.0
 120.0
u: 2-element Vector{SVector{6, Float64}}:
 [10.0, 5.0, 0.0, 0.0, 1.0, 0.0]
 [-107.58665975609732, 88.69309431302517, 0.0, -0.9721438883215371, 0.852999481284634, 0.0]

julia> solc = solve(ensemble_prob, OrdinaryDiffEq.Tsit5(), EnsembleThreads(), trajectories=size(init,2), adaptive=false, dt=0.1, save_everystep=false); solc.u[1]
retcode: Success
Interpolation: 1st order linear
t: 2-element Vector{Float64}:
   0.0
 120.0
u: 2-element Vector{SVector{6, Float64}}:
 [10.0, 5.0, 0.0, 0.0, 1.0, 0.0]
 [-107.5866597439811, 88.6930943126539, 0.0, -0.9721438870201816, 0.8529994812451269, 0.0]

julia> solc = solve(ensemble_prob, OrdinaryDiffEq.Tsit5(), EnsembleThreads(), trajectories=size(init,2), adaptive=false, dt=0.5, save_everystep=false); solc.u[1]
retcode: Success
Interpolation: 1st order linear
t: 2-element Vector{Float64}:
   0.0
 120.0
u: 2-element Vector{SVector{6, Float64}}:
 [10.0, 5.0, 0.0, 0.0, 1.0, 0.0]
 [-107.58667079704296, 88.69309425836792, 0.0, -0.9721450218969909, 0.8529994754845636, 0.0]

julia> solc = solve(ensemble_prob, OrdinaryDiffEq.Tsit5(), EnsembleThreads(), trajectories=size(init,2), adaptive=false, dt=1.0, save_everystep=false); solc.u[1]
retcode: Success
Interpolation: 1st order linear
t: 2-element Vector{Float64}:
   0.0
 120.0
u: 2-element Vector{SVector{6, Float64}}:
 [10.0, 5.0, 0.0, 0.0, 1.0, 0.0]
 [-107.58659050040124, 88.69309454053698, 0.0, -0.9721367659488884, 0.8529995067747347, 0.0]

julia> solc = solve(ensemble_prob, OrdinaryDiffEq.Tsit5(), EnsembleThreads(), trajectories=size(init,2), adaptive=false, dt=2.0, save_everystep=false); solc.u[1]
retcode: Success
Interpolation: 1st order linear
t: 2-element Vector{Float64}:
   0.0
 120.0
u: 2-element Vector{SVector{6, Float64}}:
 [10.0, 5.0, 0.0, 0.0, 1.0, 0.0]
 [-107.58670131837438, 88.6930913406193, 0.0, -0.9721478839313856, 0.852999193892342, 0.0]

julia> solc = solve(ensemble_prob, OrdinaryDiffEq.Tsit5(), EnsembleThreads(), trajectories=size(init,2), adaptive=false, dt=5.0, save_everystep=false); solc.u[1]
retcode: Success
Interpolation: 1st order linear
t: 2-element Vector{Float64}:
   0.0
 120.0
u: 2-element Vector{SVector{6, Float64}}:
 [10.0, 5.0, 0.0, 0.0, 1.0, 0.0]
 [-107.58696211105097, 88.69310141063117, 0.0, -0.9721823534177194, 0.8529983810632259, 0.0]
```

There's minor discrepancy between their results, which indicates that we may greatly enlarge the default `traj_dt` even to ~2, and there would be a great speedup with hardly accuracy loss 😋. Very good news!

**Comment by TheStarAlight** [comment]
@kfwu Hey, the developers of DiffEqGPU responded and answered my questions, now the latest `dev` version uses adaptive method for both CPU and GPU to solve the trajectories and uses `traj_rtol` to specify the accuracy, using default value is just appropriate. The cost of the test now reduces from 21m to 4m on my computer. Have a try!

**Comment by TheStarAlight** [comment]
@kfwu If you have other feature requests on this issue, please let me know :D Open another issue if you have feature requests or problems in other aspects.
The issue would keep open until the merge of pull request #14 (i.e., release of v1.4)

**Comment by kfwu** [comment]
> @kfwu Hey, the developers of DiffEqGPU responded and answered my questions, now the latest `dev` version uses adaptive method for both CPU and GPU to solve the trajectories and uses `traj_rtol` to specify the accuracy, using default value is just appropriate. The cost of the test now reduces from 21m to 4m on my computer. Have a try!

Apology for my late reply, trying to connect to github from home using Gehua's Ethernet is no joy :(.
I'd love to test the newer version from home, and thank you for the effort you have pour into. cheers mate!
And I might also have to apology for not able to give TDSE results at the moment for I'm running every code I have on a 9300H laptop. I was wondering if you'd like to run some TDSE codes yourself, I used a public available package 'Qprop' which can be easily set-up, and I'm open to discussion if there were any further problem (If you don't mind, you can shoot me an email at kefeiwu@foxmail.com, which I could access anytime).
Thanks again for the package and I wish you and this programme all the best
Kefei

**Comment by TheStarAlight** [comment]
@kfwu Thank you very much! I know about qprop which is a good package for performing TDSE simulation.
Recently I found some bugs in this program when running examples written by myself, and I'm trying to fix them one by one😢. I will do my best to make it a useful package for trajectory simulation!
btw, you may try the GitHub app, which avoids the problem that GitHub is usually unavailable in China.
Thank you for your time and I hope that we can keep in touch in the future.

Best Regards,
Mingyu Zhu
